[project]
name = "phi_cloud_action"
version = "1.4.2"
description = "使用Python实现的Phigros云端数据操作"
authors = [
    {name = "wms26", email = "2652015696@qq.com"},
]
dependencies = [
    "requests>=2.32.3", 
    "pycryptodome>=3.21.0", 
    "colorlog>=6.9.0",
    ]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "GPL-3.0"}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
phi_cloud_action = ["data/info/*.tsv","data/info/*.txt",]

[tool.setuptools.packages]
find = {where = ["."], exclude = ["tests*"]} 